### PR TITLE
Fix IE11

### LINKED ISSUE #6: Cannot be used in IE11 w/Intl.js polyfill
Not sure if this is the only blocker for IE11 support, but I get this error loading my app and the demo in IE11 with the [Intl.js polyfill](https://github.com/andyearnshaw/Intl.js/).

```
SCRIPT438: Object doesn't support property or method 'isFinite'
```

I did some research and found that `Number.isFinite` is not implemented in IE11. Could you use `isFinite` instead? I read that they are not 100% the same.

### PR DESCRIPTION
**Pull request by joefiorini**
Fixes #6

### CODE REVIEW

**Comment by dbrans** [comment]
@aokolish @joefiorini 
`global isFinite` and `Number.isFinite` are [slightly different](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/isFinite#Examples).

Would you mind writing a `function numberIsFinite` that uses `Number.isFinite` if it's there and otherwise uses the global `isFinite` but special-cases anyString => false and null => false?

**Comment by joefiorini** [comment]
@dbrans how about we just use the polyfill suggested on that page? https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/isFinite#Polyfill

**Comment by dbrans** [comment]
@joefiorini perfect. Do you or @aokolish want to update this PR?

**Comment by joefiorini** [comment]
@dbrans i'll get to it tomorrow

**Comment by joefiorini** [comment]
@dbrans turns out lodash includes this polyfill, so I went ahead and used that instead (using a package that includes just that function for now).

**Pull request merged**
