### PR TITLE
Fix command key combos

### LINKED ISSUE #4: unable to tab through fields in Safari
Not sure why, but I cannot tab through fields in Safari.

### LINKED ISSUE #5: Some browser key combinations are prevented
Example:
1. Open up the demo in Firefox (on a Mac...not sure about Windows)
2. Press Command + T to open a new tab

**Expected:** opens a new tab
**Result:** does nothing

Same thing applies to opening a new window (Command + N).

Command + ~ (to switch between open windows) works on Firefox, but does not work in Safari.

Command + L (to go to the address bar) also does not work in Firefox.

### PR DESCRIPTION
**Pull request by joefiorini**
Fixes #5

### CODE REVIEW

**Comment by dbrans** [comment]
@aokolish Is there actually an issue? I ask because #4 is closed.

**Comment by aokolish** [comment]
honestly, I'm not sure at this point

**Comment by dbrans** [comment]
Ok. Closing for now. Feel free to reopen if you find this is still an issue.

**Comment by joefiorini** [comment]
@dbrans @aokolish I reproduced it earlier today. Not very hard, just run the demo server and hit it in Safari, then try one of the key combinations mentioned in the linked issue.

**Comment by joefiorini** [comment]
@dbrans I don't have a reopen button because I'm not an admin. Can you please reopen this or give me permissions to?

**Comment by joefiorini** [comment]
Also, this fixes #5 not #4

**Comment by dbrans** [comment]
Hey @joefiorini I'm not sure how this PR which checks for TAB and ENTER addresses #5 which talks about `Command + T`.

**Comment by joefiorini** [comment]
@dbrans You were correct sir, that was the wrong commit. I believe I have the right one now. Look better?

**Comment by dbrans** [comment]
Hey @joefiorini this breaks pasting, CTRL-V, doesn't it?

**Comment by joefiorini** [comment]
@dbrans the problem is with the `preventDefault` that's happening. I moved the check into code that already sets `preventDefault` to `false`, making sure the handler always runs in its entirety. Is that better?

**Comment by dbrans** [comment]
Thank you!

**Pull request merged**
